name: Test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version check
        run: | 
          aws --version
